#!/usr/bin/env bash

# init.d script for roost service on debian

# FIXME Add these tags http://wiki.debian.org/LSBInitScripts

### BEGIN INIT INFO
# Provides:          roost
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PIDFILE=/var/run/twist.pid

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --quiet --pidfile $PIDFILE \
      --exec /usr/bin/twistd -- --pidfile /var/run/twistd.pid \
      -y $ROOST_HOME/roost/main.py
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --quiet --pidfile $PIDFILE 
    ;;
  *)
    echo "Usage: /etc/init.d/roost.sh {start|stop}"
    exit 1
    ;;
esac

exit 0
