#!/bin/bash

cd `dirname $0`/..

# Generates a debian package using fpm
# https://github.com/jordansissel/fpm/wiki

fpm -d python-setuptools -d python-twisted --after-install deb/after_install -s python -t deb setup.py
