# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# Run JS and CoffeeScript files in a typical Rails 3.1 fashion, placing Underscore templates in app/views/*.jst
# Your spec files end with _spec.{js,coffee}.

spec_location = "spec/js/%s_spec"

# uncomment if you use NerdCapsSpec.js
# spec_location = "spec/javascripts/%sSpec"

guard 'jasmine-headless-webkit', {:colors => true} do
  watch(%r{^public/js/(.*)\.js$}) { '*.js' }
  watch(%r{^spec/javascripts/(.*)_spec\..*}) { '*.js' }
end

